<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{
    protected $fillable=['body','user_id'];

    public function question(){
        return $this->belongsTo(Question::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function getBodyHtmlAttribute(){
        return \Parsedown::instance()->text($this->body);
    }
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function($answer){
            $answer->question->increment('answers_count');
//            $answer->question->save();
        });
        static::deleted(function($answer){
            $question=$answer->question;
            $question->decrement('answers_count');
            if($question->best_answer_id === $answer->id){
                $question->best_answer_id=NULL;
                $question->save();
            }
//            $answer->question->save();
        });
    }
    public function getStatusAttribute(){
        return $this->id===$this->question->best_answer_id ? 'vote-accept':'';
//        if($this->answers_count > 0){
//            if($this->best_answer_id){
//                return "answered-accepted";
//            }
//            return "answered";
//        }
//        return "unanswered";
    }
    public function getCreateDateAttribute(){
        return $this->created_at->diffForHumans();
    }

}
